### ISSUE TITLE
DOESN'T WORK AS OF 10/2023

### ISSUE THREAD

**Issue by xousef** [DrelezTM/StickerWhatsAppBOT#9]
DOESN'T WORK AS OF 10/2023

**Comment by DrelezTM** [comment]
hi,
thank you for reporting the error,

- you can uninstall your whatsapp-web.js first by
```sh
npm uninstall whatsapp-web.js
```
- then you delete the `.wwebjs_auth` folder
- then install `whatsapp-web.js` version `1.23.1-alpha.5` by way of:
```sh
npm i whatsapp-web.js@1.23.1-alpha.5
```
- then add the script below to the client
```js
webVersionCache: {
    type: 'remote',
    remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2407.3.html`,
}
```
so that it becomes like this
```js
const client = new Client({
    restartOnAuthFail: true,
    puppeteer: {
        headless: true,
        args: [ '--no-sandbox', '--disable-setuid-sandbox' ]
    },
    webVersionCache: { // this
        type: 'remote',
        remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2407.3.html`,
    },
    ffmpeg: './ffmpeg.exe',
    authStrategy: new LocalAuth({ clientId: "client" })
});
```
- then run your bot by typing the command:
```sh
npm run start
```
or you can also install the latest update ([Click Here](https://github.com/DrelezTM/StickerWhatsAppBOT/commit/25affaa99dddf96fff7784f1952b66e3d4ef0168)) from us
